version: 1.2
workflows:

   primaryDescriptorPath: scatterWrapper_MitoPipeline_v2_5.wdl
name: AlignAndCallR1_v2_5_Single
 - subclass: WDL
   primaryDescriptorPath: AlignAndCallR1_v2_5_Single.wdl
name: AlignAndCallR2_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: AlignAndCallR2_v2_5_Single.wdl
name: LiftoverTools_v2_5_Single
 - subclass: WDL
   primaryDescriptorPath: LiftoverTools_v2_5_Single
name: MongoTasks_v2_5_Single
 - subclass: WDL
   primaryDescriptorPath: MongoTasks_v2_5_Single.wdl

name: ProduceSelfReferenceFiles_v2_5_Single
 - subclass: WDL
 
   primaryDescriptorPath: ProduceSelfReferenceFiles_v2_5_Single.wdl
name: fullMitoPipeline_v2_5_Single
 - subclass: WDL
   primaryDescriptorPath: fullMitoPipeline_v2_5_Single.wdl
name: scatterWrapper_MitoPipeline_v2_5
 - subclass: WDL
